#!/bin/zsh
set -xe

DOT_LOCAL=$1
NAME=${DOT_LOCAL:h:h:t}
shift

CANT_COMPILE_HTOP=(centos-6.6 centos-6.7 centos-6.8 centos-6.9)

for tag in $@; do
    IMAGE=nuimk/nmkpkg:$tag
    TAR=nmkpkg-$tag-$NAME.tar
    if [[ ${CANT_COMPILE_HTOP[(r)$tag]} == $tag ]]; then
        OPTIONS=(--no-htop)
    else
        OPTIONS=
    fi
    CID=$(docker run -d $IMAGE $OPTIONS $DOT_LOCAL)
    docker wait $CID
    docker cp $CID:/local.tar.gz $TAR.gz
    gunzip $TAR.gz
    xz $TAR
    docker rm $CID
done

