steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - builder
    - $_DOCKER_TAG
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder
    # - --no-htop
    # - --no-tmux
    # - --no-zsh
    - --name
    - $_TAR_NAME
    - /nmk-local
  timeout: 600s
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - -h
    - 'Content-Type: application/octet-stream'
    - -h
    - 'Cache-Control:no-cache,max-age=0,no-transform'
    - cp
    - ${_TAR_NAME}.tar.xz
    - gs://nmk.nuimk.com/nmkpkg
substitutions:
    _DOCKER_TAG: ubuntu-18.04 # default value
    _TAR_NAME:   tmux-3.1b--ubuntu-18.04

