steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - builder
    - $_DOCKER_TAG
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder
    # - --no-ag
    # - --no-htop
    # - --no-tmux
    # - --no-zsh
    - --name
    - $_TAR_NAME
    - $_LOCAL_PATH
  timeout: 600s
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmkpkg/cloudbuild"
    paths:
      - ${_TAR_NAME}.tar.gz
substitutions:
    _LOCAL_PATH: /home/nui/.nmk/local # default value
    _DOCKER_TAG: ubuntu-18.04 # default value
    _TAR_NAME:   ubuntu-18.04--zsh-5.7.1-tmux-2.9--nui

