#!/bin/sh
set -ex

PROJECT=nuimk-io

gcloud --project $PROJECT compute instances create nmkpkg \
    --boot-disk-size 20GB \
    --boot-disk-type pd-ssd \
    --image-family debian-9 \
    --image-project debian-cloud \
    --machine-type n1-highcpu-2 \
    --scopes=storage-full \
    --service-account nmkpkg@nuimk-io.iam.gserviceaccount.com \
    --zone us-central1-a \
    --preemptible
gcloud --project $PROJECT compute scp \
    --plain \
    --strict-host-key-checking no \
    --zone us-central1-a \
    cloud-setup nui@nmkpkg:
gcloud --project $PROJECT compute ssh \
    --plain \
    --strict-host-key-checking no \
    --zone us-central1-a \
    nui@nmkpkg
