steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - builder
    - $_DOCKER_TAG
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder
    # - --no-htop
    - --name
    - $_TAR_NAME
    - $_LOCAL_PATH
  timeout: 600s
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmkpkg/cloudbuild"
    paths:
      - ${_TAR_NAME}.tar.gz
substitutions:
    _LOCAL_PATH: /root/.nmk/local # default value
    _DOCKER_TAG: centos-7.0.1406 # default value
    _TAR_NAME:   nmkpkg-centos-7.0-root

