#!/bin/sh
set -ex

PROJECT=nuimk-io
ZONE=us-central1-a

gcloud compute instances create nmkpkg \
    --boot-disk-size 20GB \
    --boot-disk-type pd-ssd \
    --image-family debian-9 \
    --image-project debian-cloud \
    --machine-type n1-highcpu-2 \
    --scopes=storage-full \
    --service-account nmkpkg@nuimk-io.iam.gserviceaccount.com \
    --preemptible \
    --project $PROJECT \
    --zone $ZONE
gcloud compute scp \
    cloud-setup nui@nmkpkg: \
    --plain \
    --strict-host-key-checking no \
    --project $PROJECT \
    --zone $ZONE
gcloud compute ssh nui@nmkpkg \
    --command="env DEBIAN_FRONTEND=noninteractive sh cloud-setup" \
    --plain \
    --strict-host-key-checking no \
    --project $PROJECT \
    --zone $ZONE
gcloud compute instances list \
    --project $PROJECT
