steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - builder
    - $_DOCKER_TAG
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder
    - /root/.nmk/local
    - --name
    - $_TAR_NAME
  timeout: 600s
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmkpkg"
    paths:
      - ${TAR_NAME}.tar.gz
substitutions:
    _LOCAL_PATH: /root/.nmk/local # default value
    _DOCKER_TAG: centos-7.5.1804 # default value
    _TAR_NAME: nmkpkg

